import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { ProdProvider } from './components/contexts/ProdContext'; // Ajuste o caminho conforme necessário

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "New ecommerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <ProdProvider>
          {children}
        </ProdProvider>
      </body>
    </html>
  );
}
